name: Sample Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger with inputs
    inputs:
      stage_python_test:
        description: 'Run Production Python Test'
        required: false
        default: false
        type: boolean
      remove_deployment:
        description: 'Run Remove Deployment'
        required: false
        default: false
        type: boolean
      setup_stage_environment:
        description: 'Run Setup Stage Environment'
        required: false
        default: false
        type: boolean

jobs:
  # Gate Stage
  gate_js_test:
    name: JavaScript Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript Tests
        run: |
          echo "Running JavaScript tests..."

  gate_python_test:
    name: Python Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python Tests
        run: |
          echo "Running Python tests..."

  # Build Stage
  build_js:
    name: JavaScript Build
    runs-on: ubuntu-latest
    needs: [gate_js_test, gate_python_test]  # Run after gate stage completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build JavaScript
        run: |
          echo "Building JavaScript application..."

  build_push_artifact:
    name: Build & Push Artifact
    runs-on: ubuntu-latest
    needs: [gate_js_test, gate_python_test]  # Run after gate stage completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Artifact
        run: |
          echo "Building artifact..."

      - name: Push Artifact
        run: |
          echo "Pushing artifact..."

  # Stage Environment Jobs with Manual Control
  stage_python_test:
    name: Production Python Test
    runs-on: ubuntu-latest
    needs: [build_js, build_push_artifact]  # Only run after gate and build stages
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.stage_python_test == 'true' }}  # Compare as strings
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Production Python Tests
        run: |
          echo "Running production-level Python tests..."

  remove_deployment:
    name: Remove Deployment
    runs-on: ubuntu-latest
    needs: [build_js, build_push_artifact]  # Only run after gate and build stages
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.remove_deployment == 'true' }}  # Compare as strings
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Deployment
        run: |
          echo "Removing previous deployment..."

  setup_stage_environment:
    name: Setup Stage Environment
    runs-on: ubuntu-latest
    needs: [build_js, build_push_artifact]  # Only run after gate and build stages
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.setup_stage_environment == 'true' }}  # Compare as strings
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Stage Environment
        run: |
          echo "Setting up stage environment..."
